version: "3.4"

services:
    client:
        build: ./
        container_name: instruction-sheet
        ports:
            - "8080:8080"
        expose:
            - "8080"
        volumes:
            - ./:/app
        tty: true
        stdin_open: true
